# Generated by Django 3.0.4 on 2020-03-20 16:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=8)),
                ('iswc', models.CharField(max_length=50)),
            ],
        ),
    ]
