# Generated by Django 3.0.4 on 2020-03-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='iswc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='musicalwork',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
